"let mapleader = "\"
:set incsearch
:set nu
":set expandtab
:set tabstop=3
:set shiftwidth=3
:set autoindent
:set smartindent
:syn on
:set noswapfile
:set hlsearch
set mouse=a
set wrap
set linebreak

set list
set listchars+=tab:┊\ 
set listchars+=eol:\ 
"set listchars+=space:·

"set cursorcolumn
"set cursorline

nnoremap <C-t>     :tabnew<CR>
inoremap <C-t>     <Esc>:tabnew<CR>

" nmap <silent> <A-Up> :wincmd k<CR>
" nmap <silent> <A-Down> :wincmd j<CR>
" nmap <silent> <A-Left> :wincmd h<CR>
" nmap <silent> <A-Right> :wincmd l<CR>

set splitbelow
set splitright




"folding settings
"let php_folding=1
"set foldmethod=syntax   "fold based on indent
set foldnestmax=3      "deepest fold is 10 levels
set nofoldenable        "dont fold by default
set foldlevel=1         "this is just what i use
"set foldlevelstart=2

set nocompatible               " be iMproved
"filetype off                   " required!

set rtp+=~/.vim/bundle/vundle
call vundle#rc()

" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'

" My Bundles here:

Plugin 'tomtom/tcomment_vim'
Plugin 'scrooloose/nerdtree'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'scrooloose/syntastic'
Plugin 'zefei/vim-wintabs'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'chrisbra/vim-diff-enhanced'
Plugin 'altercation/vim-colors-solarized'

syntax enable
" set background=dark
" colorscheme solarized
colorscheme desert

" let g:solarized_diffmode="high"

" if &diff
" 	colorscheme evening
" endif

"filetype plugin indent on     " required!

:set encoding=utf-8

:set tenc=utf8

:set isprint=

if !has('gui_running')
	set t_Co=256
endif

"let g:nerdtree_tabs_open_on_console_startup=1
map <C-n> :NERDTreeToggle<CR>
"autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

highlight HLONE cterm=NONE ctermbg=green ctermfg=white
highlight HLTWO cterm=NONE ctermbg=blue ctermfg=white

nnoremap q :mat HLONE "<C-R><C-W>"<CR>
nnoremap Q :2mat HLTWO "<C-R><C-W>"<CR>
nnoremap qq :mat none<CR>
nnoremap QQ :2mat none<CR>



nmap <silent> <C-u> :split<CR>
nmap <silent> <C-i> :vsplit<CR>
nmap <silent> <C-o> :CtrlPBuffer<CR>

let g:ctrlp_cmd='CtrlP :pwd'

" nmap <silent> <C-p> :CtrlP<CR>
let g:ctrlp_working_path_mode = 'ra'

" menu completion in command mode on <tab>
set wildmenu
" <tab> cycles between all matching choices.
set wildmode=full
" ignore these files when completing
set wildignore+=*.o,*.obj,.git,*.pyc,node_modules


"set wildchar=<Tab> wildmenu wildmode=full
set wildcharm=<C-Z>
nnoremap <F10> :b <C-Z>

" Mappings to access buffers (don't use "\p" because a
" delay before pressing "p" would accidentally paste).
" \l       : list buffers
" \b \f \g : go back/forward/last-used
" \1 \2 \3 : go to buffer 1/2/3 etc
nnoremap <Leader>l :ls<CR>
nnoremap <Leader>b :bp<CR>
nnoremap <Leader>f :bn<CR>
nnoremap <Leader>g :e#<CR>
nnoremap <Leader>1 :1b<CR>
nnoremap <Leader>2 :2b<CR>
nnoremap <Leader>3 :3b<CR>
nnoremap <Leader>4 :4b<CR>
nnoremap <Leader>5 :5b<CR>
nnoremap <Leader>6 :6b<CR>
nnoremap <Leader>7 :7b<CR>
nnoremap <Leader>8 :8b<CR>
nnoremap <Leader>9 :9b<CR>
nnoremap <Leader>0 :10b<CR>

let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\'

:set tabstop=3

"set noshowmode

"write everything
set autowriteall

" use <ctrl> hjkl to move between buffers
map <c-j> :bp <CR>
map <c-k> :bn <CR>
map <c-h> :bfirst <CR>
map <c-l> :blast <CR>

highlight DiffAdd    cterm=NONE ctermfg=0 ctermbg=2
highlight DiffDelete cterm=NONE ctermfg=0 ctermbg=1
highlight DiffChange cterm=NONE ctermfg=0 ctermbg=2
highlight DiffText   cterm=NONE ctermfg=0 ctermbg=6

autocmd FilterWritePre * if &diff | setlocal wrap< | endif

