#!/bin/bash
DISTRO=unknown
# Determine OS platform
UNAME=$(uname | tr "[:upper:]" "[:lower:]")
# If Linux, try to determine specific distribution
if [ "$UNAME" == "linux" ]; then
    # If available, use LSB to identify distribution
    if [ -f /etc/lsb-release -o -d /etc/lsb-release.d ]; then
        DISTRO=$(lsb_release -i | cut -d: -f2 | sed s/'^\t'//)
    # Otherwise, use release info file
    else
        DISTRO=$(ls -d /etc/[A-Za-z]*[_-][rv]e[lr]* | grep -v "lsb" | cut -d'/' -f3 | cut -d'-' -f1 | cut -d'_' -f1)
    fi
fi
# For everything else (or if above failed), just use generic identifier
[ "$DISTRO" == "" ] && DISTRO=$UNAME
unset UNAM

if ! [ -x "$(command -v curl)" ]; then
  if [ "$DISTRO" == "Ubuntu" ]; then
    sudo apt install -y git curl
  else 
    echo 'Error: curl is not installed.' >&2
    exit 1
  fi
fi

if ! [ -x "$(command -v git)" ]; then
  echo 'Error: git is not installed.' >&2
  exit 1
fi

H=$(uname -n)
ME=$(whoami)

if [ -f ~/.ssh/id_rsa ]; then
  echo 'rsa keys exits'
else 
  mkdir -p ~/.ssh
  ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N '' -C "$ME@$H" 
fi

read -p "Copy keys to github (y/N) " copygithub

if [ "$copygithub" == "y" ]; then
  pubkey=$(<~/.ssh/id_rsa.pub)

  json="{\"title\": \"$ME@$H\",\"key\": \"$pubkey\"}"
  
  curl -u "rubimayank" -H "Content-Type: application/json" -X POST -d "$json" https://api.github.com/user/keys
fi

cd ~

if [ -d ~/.dotfiles ]; then
  echo 'dotfile exits'
else 
  if [ "$copygithub" == "y" ]; then
    git clone git@github.com:rubimayank/.dotfiles.git
  else 
    git clone https://github.com/rubimayank/.dotfiles.git
  fi
fi

cd ~/.dotfiles

read -p "Enter Profile: " profile
echo "Installing $profile profile"
~/.dotfiles/profiles/$profile
