#!/bin/bash

if ! [ -x "$(command -v curl)" ]; then
  echo 'Error: curl is not installed.' >&2
  exit 1
fi

if ! [ -x "$(command -v git)" ]; then
  echo 'Error: git is not installed.' >&2
  exit 1
fi

H=$(uname -n)
mkdir -p ~/.ssh
ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N '' -C "mohit@$H" 
pubkey=$(<~/.ssh/id_rsa.pub)

json="{\"title\": \"mohit@$H\",\"key\": \"$pubkey\"}"
  
curl -u "mohitmayank" -H "Content-Type: application/json" -X POST -d "$json" https://api.github.com/user/keys

cd ~

git clone git@github.com:mohitmayank/.dotfiles.git

cd ~/.dotfiles
