#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

rm -f ~/.gitconfig
ln -s $DIR/gitconfig ~/.gitconfig 

rm -f ~/.gitignore
ln -s $DIR/gitignore ~/.gitignore

rm -r ~/.config/clipit/clipitrc
ln -s $DIR/clipitrc ~/.config/clipit/clipitrc

mkdir -p ~/.config/geany
rm -rf ~/.config/geany/colorschemes
ln -s $DIR/geany/colorschemes ~/.config/geany/colorschemes

mkdir -p ~/.config/Code/User
rm -rf ~/.config/Code/User/settings.json
ln -s $DIR/vscode ~/.config/Code/User/settings.json