#!/bin/bash

##Add self to suoders
ME=$(whoami)
sudo sh -c "echo '$ME ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/$ME"

sudo yum install –y epel-release

if [ -x "$(command -v yum-config-manager)" ]; then
	yum-config-manager --enable epel
fi

sudo yum -y install curl wget p7zip tree htop
sudo yum -y install vim git tmux dos2unix
