#!/bin/bash
sudo snap install snap-store
sudo snap install slack --classic
sudo snap install postman
sudo snap install code --classic
sudo snap install chromium
sudo snap install opera
sudo snap install insomnia
sudo snap install mari0
# sudo snap install gimp
sudo snap install inkscape
sudo snap install vlc
mkdir -p ~/snap/vlc/common/.cache/vlc
sudo snap install libreoffice
sudo snap install zeal-casept
sudo snap install skype --classic
sudo snap install shotcut --classic
sudo snap install telegram-desktop
sudo snap install glimpse-editor
