#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

rm -f ~/.tmux.conf
ln -s $DIR/conf/tmux.conf ~/.tmux.conf

mkdir -p ~/.tmux/plugins

if [ -d ~/.tmux/plugins/tpm ]; then
  #do nothing
  :
else 
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

~/.tmux/plugins/tpm/scripts/install_plugins.sh

sudo gem install tmuxinator

mkdir -p ~/.config
if [[ -L ~/.config/tmuxinator ]]; then
  unlink ~/.config/tmuxinator
else
  rm -rf ~/.config/tmuxinator
fi

ln -s $DIR/conf/tmuxinator ~/.config/tmuxinator
