#!/bin/bash

##variables
UBUNTUCODE=$(lsb_release -cs)

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

$DIR/ubuntu

##setup home
sudo chown "$ME":"$ME" /data
rm -rf ~/Documents
rm -rf ~/Downloads
rm -rf ~/Music
rm -rf ~/Pictures
rm -rf ~/Videos

mkdir -p /data/Documents
mkdir -p /data/Downloads
mkdir -p /data/Music
mkdir -p /data/Pictures
mkdir -p /data/Videos
mkdir -p /data/bin
mkdir -p /data/Movies
mkdir -p /data/Recovery
mkdir -p /data/tmp/scrot

ln -s /data/Documents ~/Documents
ln -s /data/Downloads ~/Downloads
ln -s /data/Music ~/Music
ln -s /data/Pictures ~/Pictures
ln -s /data/Videos ~/Videos
ln -s /data/bin ~/bin
ln -s /data/Movies ~/Movies
ln -s /data/Recovery ~/Recovery
ln -s /data/tmp ~/tmp


##install ubuntu universe packages
sudo apt-get install -y gparted python-pip
sudo apt-get install -y geany meld geany-plugins httpie
sudo apt-get install -y gimp inkscape
sudo apt-get install -y filezilla chromium-browser clipit
sudo apt-get install -y vlc calibre  
sudo apt-get install -y openvpn network-manager-openvpn-gnome	
sudo apt-get install -y openssh-server	
sudo apt-get install -y ttf-mscorefonts-installer	
sudo apt-get install -y baobab #Disk Usage Analyzer


pip install --upgrade pip
pip install rtv

##Remove packages
sudo apt-get remove -y --purge thunderbird evince evince-common parole pidgin mousepad gnome-sudoku


##install google chrome
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O /tmp/google-chrome-stable_current_amd64.deb
sudo gdebi -n /tmp/google-chrome-stable_current_amd64.deb

##install steam
#wget https://steamcdn-a.akamaihd.net/client/installer/steam.deb
#sudo gdebi -n steam.deb


##add repos
sudo add-apt-repository -y ppa:libreoffice/ppa
sudo sh -c 'echo "deb http://deb.opera.com/opera/ stable non-free" >> /etc/apt/sources.list.d/opera.list'
sudo sh -c 'wget -O - http://deb.opera.com/archive.key | apt-key add -'
sudo add-apt-repository -y ppa:micahflee/ppa
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo add-apt-repository ppa:zeal-developers/ppa
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
sudo add-apt-repository ppa:twodopeshaggy/jarun


sudo apt-get update

sudo apt-get install googler

##vscode
sudo apt-get install code 
sudo sh -c 'echo "fs.inotify.max_user_watches=524288" >> /etc/sysctl.conf'
sudo sysctl -p

##zeal offline docs
sudo apt-get install zeal 

##libre office latest
sudo apt install libreoffice

##install opera
sudo apt-get install -y opera-stable

##TOR
sudo apt-get install -y torbrowser-launcher

##Postman
wget https://dl.pstmn.io/download/latest/linux64 -O /tmp/postman.tar.gz
sudo tar -xzf /tmp/postman.tar.gz -C /opt
rm postman.tar.gz
sudo ln -s /opt/Postman/Postman /usr/bin/postman
cat > ~/.local/share/applications/postman.desktop <<EOL
[Desktop Entry]
Encoding=UTF-8
Name=Postman
Exec=postman
Icon=/opt/Postman/resources/app/assets/icon.png
Terminal=false
Type=Application
Categories=Development;
EOL


##Buu Crawler (http://beamusup.com/seo-analytics-cro-tools/)
cd /tmp
sudo apt-get install -y default-jdk
sudo mkdir -p /opt/buu
sudo wget https://s3-eu-west-1.amazonaws.com/buu/buu.jar -O /opt/buu/buu.jar
cat > /tmp/buu <<'EOL'
#!/bin/bash
java -Xms512m -Xmx4048m -jar /opt/buu/buu.jar
EOL
sudo mv /tmp/buu /opt/buu/buu
sudo chmod +x /opt/buu/buu
sudo chown root:root /opt/buu/buu
sudo ln -s /opt/buu/buu /usr/bin/buu
sudo cp $DIR/../assets/crawler.png /opt/buu/crawler.png
cat > ~/.local/share/applications/buu.desktop <<EOL
[Desktop Entry]
Encoding=UTF-8
Name=BUU SEO Crawler
Exec=buu
Icon=/opt/buu/crawler.png
Terminal=false
Type=Application
Categories=Internet;
EOL




##copy touch toggle
cat > /tmp/touchtoggle <<'EOL'
#!/bin/sh
synclient touchpadoff=$(synclient -l | grep TouchpadOff | awk '{print $3==0?1:0}')
EOL
sudo mv /tmp/touchtoggle /usr/bin/touchtoggle
sudo chmod +x /usr/bin/touchtoggle
sudo chown root:root /usr/bin/touchtoggle


##install docker
sudo apt-get install -y docker-ce
sudo usermod -aG docker $(whoami)


##install docker compose
sudo curl -L https://github.com/docker/compose/releases/download/1.20.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose


##GRUB
awk '{sub(/GRUB_CMDLINE_LINUX_DEFAULT=\".*?\"/,"GRUB_CMDLINE_LINUX_DEFAULT=\"\"")}1' /etc/default/grub > /tmp/grubdefault
sudo cp /tmp/grubdefault /etc/default/grub
sudo update-grub2

##Xubuntu shortcuts
xfconf-query --create --channel xfce4-keyboard-shortcuts --property '/commands/custom/<Super>L' --type string --set 'xflock4'
xfconf-query --create --channel xfce4-keyboard-shortcuts --property '/commands/custom/<Super>E' --type string --set 'geany'
xfconf-query --create --channel xfce4-keyboard-shortcuts --property '/commands/custom/<Super>Q' --type string --set 'thunar'
xfconf-query --create --channel xfce4-keyboard-shortcuts --property '/commands/custom/<Super>slash' --type string --set 'touchtoggle'
xfconf-query --create --channel xfce4-keyboard-shortcuts --property '/commands/custom/<Shift>Print' --type string --set 'xfce4-screenshooter -r'
xfconf-query --create --channel xfce4-keyboard-shortcuts --property '/commands/custom/<Super>T' --type string --set 'xfce4-terminal --maximize'

##XFCE WM Shortcuts
xfconf-query --create --channel xfce4-keyboard-shortcuts --property '/xfwm4/custom/<Super>Left' --type string --set 'tile_left_key'
xfconf-query --create --channel xfce4-keyboard-shortcuts --property '/xfwm4/custom/<Super>Right' --type string --set 'tile_right_key'
xfconf-query --create --channel xfce4-keyboard-shortcuts --property '/xfwm4/custom/<Super>Up' --type string --set 'tile_up_key'
xfconf-query --create --channel xfce4-keyboard-shortcuts --property '/xfwm4/custom/<Super>Down' --type string --set 'tile_down_key'
xfconf-query --create --channel xfce4-keyboard-shortcuts --property '/xfwm4/custom/<Super>bracketleft' --type string --set 'tile_up_left_key'
xfconf-query --create --channel xfce4-keyboard-shortcuts --property '/xfwm4/custom/<Super>bracketright' --type string --set 'tile_up_right_key'
xfconf-query --create --channel xfce4-keyboard-shortcuts --property '/xfwm4/custom/<Super>semicolon' --type string --set 'tile_down_left_key'
xfconf-query --create --channel xfce4-keyboard-shortcuts --property '/xfwm4/custom/<Super>apostrophe' --type string --set 'tile_down_right_key'
xfconf-query --create --channel xfce4-keyboard-shortcuts --property '/xfwm4/custom/<Super>equal' --type string --set 'maximize_window_key'

##XFCE Desktop config
mkdir -p ~/.config/_wallpaper
cp $DIR/../assets/wallpapers/black.png ~/.config/_wallpaper/black.png
xfconf-query -c xfce4-desktop -p '/backdrop/screen0/monitor0/workspace0/last-image' --type string -s ~/.config/_wallpaper/black.png
xfconf-query -c xfce4-desktop -p '/desktop-icons/style' --type int -s 0

sudo reboot
